name: Build and Deploy Website

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removed cache option that requires lock file

      - name: Install dependencies
        run: npm install --no-package-lock  # This will avoid looking for or creating a lock file

      - name: Install FontAwesome dependency
        run: npm install --save @fortawesome/fontawesome-free --no-package-lock

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
