name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update App.test.js
        run: |
          echo 'import { render, screen } from "@testing-library/react";
          import App from "./App";

          test("renders Trevor Jarzynka heading", () => {
            render(<App />);
            const headingElement = screen.getByText(/Trevor Jarzynka/i);
            expect(headingElement).toBeInTheDocument();
          });' > src/App.test.js

      - name: Run tests
        run: CI=true npm test

      - name: Build 
        run: npm run build
        env:
          PUBLIC_URL: https://trevorjarzynka.github.io/Personal_Website_React

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
